# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.10.3.dev62+g42faa1d.d20221010'
__version_tuple__ = version_tuple = (0, 10, 3, 'dev62', 'g42faa1d.d20221010')
