name: benchmark
on: [pull_request, push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.11.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure git safe directory
        run: |
          git config --global --add safe.directory '*'

      - name: Install local package and dependencies
        run: |
          python3 -m pip install .[test] --no-build-isolation

      - name: Run benchmark
        run: |
          python3 test/benchmark.py
